### PR TITLE
fixed spellign erors

### PR DESCRIPTION
**Pull request by voidfill**

### CODE REVIEW

**Comment by Kyza** [comment]
You misspecle `consoe`  as `console,lo()`.

**Comment by voidfill** [comment]
ok will fixed in next

**Review by Kyza — CHANGES_REQUESTED** [review]
Infintie loop iosnt' multipthreaded.

**Comment by voidfill** [comment]
image
should i just use css then?

**Comment by Kyza** [comment]
> image
> should i just use css then?

WebWQorker

**Comment by voidfill** [comment]
how

**Pull request closed without merging**
